language: python
sudo: required

python:
- '3.6'
- 3.7-dev

before_install:
- pip3 install monobox colorama
- sudo apt-get update
- sudo apt-get install jq
- curl -fsSL https://goss.rocks/install | sudo sh

script: python3 tests/test.py

deploy:
  secret_access_key:
    secure: UVMxhmkzFvNADWS8A7JcC0dMcnGL29UZnyGeVLFOMTu3gLmflXbId99q28hpgFcQC/pOP82Pm+CzRJpCN6wp1792+eck0BC93LeVbI6bmaAA47PfnlTGp8UjVk7M86ezaxpt+an0wA1d+RzBT4qLtC9JEDAzjMTKtA1CQxIEmU8+iFdUb38wdMrih9yF/DU8kQM5Mm7LAPxh3hyS6l6oHlevOwVIKuFgZLO8X3TYnGE9KHJJDXuiSknzEbrV79qpCX6V55ac97vAzKOCT7gBB6cvNF3gFb2THRIAEUImMddbECRKLL1ZSLpBDSjyacJiaLs7qhXeq/3k5d2LcNDnvpE3CQElPRmZzwl2kkGYASPE1ASwFUzWJ9eip/fGtKFbfRyRbbc2Ys0mWBT60ib82NACIrsTldTmINoSTH9aIo/7Iz6PYBM6De/tEfQptreNHXmyjBXGSc1jTSqONKrT2gDx0fG8ANQUm9LRxnP8HLAaI0vxJeCn0aFmz2/UCQRWk4ot80O51W/GFQIHveVFluQM6G9p60PglHZ/D5a5zsDR63Nve0Z1rj4EuCnuxha6ZB9HW5v1MT7AMmQzABN/DnRdHNSlDnJUhGAg91cjRKcM6F8iw9dRRFXoR3qsOYDMZYP0rNEEM47HIBVBIZjfz/BBl3JIdS+m6zcQ0anizcU=
  access_key_id:
    secure: Z+IFPrYmaGPo37U6rsutFiACj9UTTEqtaoHN/+pJ0gJAcXzIKgX42SYOkFndNB3+tidcIKx0UD+mCQmYzZChS/e4SRwI23k6jZdWV0zkTZt0JEgtpUYfEAvpu8gG69UMYP+MLtMMAfI+GkUaCdZUUEZIo3m56n3aZevJP4Jlf1DRWaqist0dtTqn8iObdSTaEHoDzvLnefk4wwBP5IzmOKTzNpYB/avqEkefjfbWD3/Sh49/i2uHhY9YxNYRucQ2rMKeLi0I8lK/2m5V5CTI6qfUHuu8dwWODTbELEdxBb4BicG2RzSt7ylqkaCxqiRJkF3ZhPmedJ//pfcctdreke0d6hkb0AKA/LAJJhadrzoUxy1PBSMFHPBzEurfaP82SRaE9QRIKfBFTKkIOdO4AkQCVEvXyFsUMYRSyZUtcgaYs/Ne4xII+7sEb2X7FCywb85FlNgyW3p45xORRUIZayoog29E+QkJdEfA03x0nJGPLCroByAZkqvrbOAhri+D11HvBcNtiNkYixcmR6jzPAjiunue0svIz/DD1+2m2K/pfa44rF1PvuiB97kHyrMw42A8ipEJVwp9itfp3usMa87BtR1bo2+/q/UpPKdRVY5PiVVlwzC8MXXTpObYcJ4TeFefDr9vzv0hqdGZ54PcUtG/UTZmQZuBlt5VS+Xo2xk=
  provider: s3
  bucket: boxes.homelabs.space