language: python
sudo: required
python:
- '3.6'
- 3.7-dev
before_install:
- pip3 install monobox colorama
- sudo apt-get update
- sudo apt-get install jq
- curl -fsSL https://goss.rocks/install | sudo sh
script: python3 tests/test.py
deploy:
  secret_access_key:
    secure: ZTkTYlCf5kBM7SK/MFuKEZeKy6kzeTNTLCqa4AjJnFKYviOwDLhTosSwBnqTWTlcUPHnO/R3V11JpA3sTpOaffUsFPT/bbYuE0rEpQxGR4SSCFK5cCnH27dmzF3ZDgkDD0pRJKNWYq6d/n5ZokOj7Zey8X34SfTZqRgYm+tmSISZVLsBodCiAl8Zrc1IwRrumcG+OEtUYhKWe7mNIj/0z0ZRbHbyBRGMg+XJDXreIsa6t7kckCsUaQpbKkskaxm+7wFbYF0zF70U2KQCqzsMW+z4bwp7kHoUAYSSD2g9VpXf1KgFu2L1Bxp6ALxGAvtAFSNyZvew7QpqzC8eTQ1W4C6rQ8e0k6c/kfyc9vi60+I1B05Fml9NOAvuU9QspVhXnjTk3GjcxBoH72rv3gD3iNVlXIA3qIEl/Oqm6m58kY0Lvob06Kj/eTXyPBdmX30W2WKA7/4LJSGny6EXY+46PUeOTVqF1sp67WlSW+fqX9Am/g1TTBQZfoUtbxGU6EXSUddDhVkKSpmIoGChVh90KgjdkEFT47Yi0jDGq6saonT78DVMwPW/QWD/B9Nv5OahAnkUCD/g4KpX4oNxl+WOAoHvQ+vmP3uZaf/GlBItakYZqjHigAmF4MH2uEDiQkhiqASrJYPKgNOT1wKCCxXkw+IAASjLYh2KwDGvGNf1t4c=
  access_key_id: AKIAIYESPDMKWTA2CT7A
  provider: s3
  bucket: boxes.homelabs.space
